// <auto-generated />
namespace KapoTechProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_Add_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_Add_database));
        
        string IMigrationMetadata.Id
        {
            get { return "202212301559208_mig_Add_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
